version: 2.1

orbs:
  slack: circleci/slack@5.1.1

executors:
  deploy-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

jobs:
  deploy_geosphere_java_backend:
    executor: deploy-executor
    steps:
      - slack/notify:
          event: always
          channel: "#circleci-deployment-query"
          custom: >
            {
              "blocks": [
                {
                  "type": "header",
                  "text": { "type": "plain_text", "text": "🚀 Java Backend Deployment Triggered!" }
                },
                {
                  "type": "section",
                  "text": { "type": "mrkdwn", "text": "*Java Backend* deployment has *started*." }
                }
              ]
            }

      - checkout

      - run:
          name: Create .ssh Directory
          command: mkdir -p ~/.ssh

      - add_ssh_keys:
          fingerprints:
            - $SSH_KEY_FINGERPRINT

      - run:
          name: Add EC2 Server to Known Hosts
          command: ssh-keyscan -H $JAVA_EC2_IP >> ~/.ssh/known_hosts

      - run:
          name: Execute Deployment Script on Java EC2
          command: ssh -o StrictHostKeyChecking=no ubuntu@$JAVA_EC2_IP "cd /GeoSphere_Java_BE && sudo sh deploy.sh"

      - slack/notify:
          event: pass
          channel: "#circleci-deployment-query"
          custom: >
            {
              "blocks": [
                {
                  "type": "header",
                  "text": { "type": "plain_text", "text": "✅ Java Deployment Successful" }
                },
                {
                  "type": "section",
                  "text": { "type": "mrkdwn", "text": "*Java Backend* has been deployed successfully! 🎉" }
                }
              ]
            }

      - slack/notify:
          event: fail
          channel: "#circleci-deployment-query"
          custom: >
            {
               "blocks": [
                 {
                   "type": "header",
                   "text": { "type": "plain_text", "text": "❌ Java Deployment Failed" }
                 },
                 {
                   "type": "section",
                   "text": { "type": "mrkdwn", "text": "*Java Backend* deployment failed! 🚨 Please check the CircleCI logs." }
                 }
               ]
             }

workflows:
  version: 2
  deploy_java_backend:
    jobs:
      - deploy_geosphere_java_backend:
          filters:
            branches:
              only:
                - main
